#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WIDM_ICT_App.Resource", IsApplication=true)]

namespace WIDM_ICT_App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int eten_array = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int groep_array = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int janee_array = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int kleur_array = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int ogen_array = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int opdracht_array = 2131034117;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Error_Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_access_time_black_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_arrow_back_black_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_import_contacts_black_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_lock_outline_black_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_black_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_person_outline_black_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_priority_high_black_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Mol = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int WIDM_Icon = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060013
			public const int ButtonVerzenden = 2131099667;
			
			// aapt resource value: 0x7f060006
			public const int RelativeLayout01 = 2131099654;
			
			// aapt resource value: 0x7f060012
			public const int ScoreText = 2131099666;
			
			// aapt resource value: 0x7f06000f
			public const int beschrijving = 2131099663;
			
			// aapt resource value: 0x7f060003
			public const int btn1 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int btn2 = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int btn_kelly = 2131099648;
			
			// aapt resource value: 0x7f060018
			public const int btn_reg_cancel1 = 2131099672;
			
			// aapt resource value: 0x7f060028
			public const int btn_reg_cancel2 = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int btn_reg_complete = 2131099689;
			
			// aapt resource value: 0x7f06001d
			public const int btn_reg_datum = 2131099677;
			
			// aapt resource value: 0x7f060019
			public const int btn_reg_next = 2131099673;
			
			// aapt resource value: 0x7f06002a
			public const int error_reg = 2131099690;
			
			// aapt resource value: 0x7f060001
			public const int gb_input = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int imageButton1 = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int imageView1 = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int imageView2 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int maxScore = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int maxTijd = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int opdrachtNr = 2131099656;
			
			// aapt resource value: 0x7f06001a
			public const int radioGroup1 = 2131099674;
			
			// aapt resource value: 0x7f060017
			public const int reg_mail = 2131099671;
			
			// aapt resource value: 0x7f06001b
			public const int reg_man = 2131099675;
			
			// aapt resource value: 0x7f060014
			public const int reg_naam = 2131099668;
			
			// aapt resource value: 0x7f06001c
			public const int reg_vrouw = 2131099676;
			
			// aapt resource value: 0x7f060015
			public const int reg_ww_1 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int reg_ww_2 = 2131099670;
			
			// aapt resource value: 0x7f06000a
			public const int relativeLayout1 = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int relativeLayout3 = 2131099661;
			
			// aapt resource value: 0x7f060024
			public const int spinner_broerzus = 2131099684;
			
			// aapt resource value: 0x7f060020
			public const int spinner_eten = 2131099680;
			
			// aapt resource value: 0x7f060011
			public const int spinner_groep = 2131099665;
			
			// aapt resource value: 0x7f06001f
			public const int spinner_kleur = 2131099679;
			
			// aapt resource value: 0x7f060021
			public const int spinner_ogen = 2131099681;
			
			// aapt resource value: 0x7f060010
			public const int spinner_opdracht = 2131099664;
			
			// aapt resource value: 0x7f060023
			public const int spinner_relatie = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int spinner_roken = 2131099682;
			
			// aapt resource value: 0x7f060025
			public const int spinner_tattoo = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int sport_tattoo = 2131099686;
			
			// aapt resource value: 0x7f060005
			public const int textView1 = 2131099653;
			
			// aapt resource value: 0x7f06001e
			public const int tv1 = 2131099678;
			
			// aapt resource value: 0x7f060027
			public const int tv2 = 2131099687;
			
			// aapt resource value: 0x7f060002
			public const int ww_input = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int opdrachtUitvoeren = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int opdrachtVerifieren = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int registeer = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int registreer2 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int spinner = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int broerzus_prompt = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int eten_prompt = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int kleur_prompt = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int ogen_prompt = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int relatie_prompt = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int roken_prompt = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int sport_prompt = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int tattoo_prompt = 2130968585;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
